export type IArticle = {
    article_id: string;
    title: string;
    link: string;
    keywords: string[] | null;
    creator: string | null;
    video_url: string | null;
    description: string | null;
    content: string;
    pubDate: string;
    image_url: string;
    source_id: string;
    source_priority: number;
    source_url: string;
    source_icon: string;
    language: string;
    country: string[];
    category: string[];
    ai_tag?: string;
    sentiment?: string;
    sentiment_stats?: string;
    ai_region?: string;
};
